### ISSUE TITLE
Integration creating tons of entities 

### ISSUE THREAD

**Issue by Kosygor** [drinfernoo/homeassistant-binance#13]
Hello just have installed You integration with configuration 
```
 binance_pool:
   domain: com
   native_currency: USD
   balances:
     - TLM
     - BUSD
   api_key: !secret binance_api_key
   api_secret: !secret binance_api_secret
```
And it just started crating tons of entities.
Did not count them and wait to see how many there are. Most of them were *_exchange. Could it be because i did no specify   `exchanges:`?
Edit: realy I did not read documentation well.... Closing
